# Generated by Django 5.0.7 on 2024-07-21 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_order_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cart_item',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='store.cartitem'),
        ),
    ]
