# Generated by Django 5.0.7 on 2024-07-21 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_order_cart_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cart_item',
        ),
        migrations.AddField(
            model_name='order',
            name='cart_item_ids',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
