# Generated by Django 5.0.7 on 2024-07-26 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_category1'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='name_en',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='name_es',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='name_fr',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
