# Generated by Django 5.0.7 on 2024-07-26 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_products_name_en_products_name_es_products_name_fr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='products',
            name='name_es',
        ),
        migrations.RemoveField(
            model_name='products',
            name='name_fr',
        ),
    ]
